version: "3"

services:
  spark-master:
    image: bitnami/spark:3.5.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=8341
      - SPARK_MASTER_WEBUI_PORT=8340
    ports:
      - "8340:8340"
      - "8341:8341"
    volumes:
      - shared-workspace:/home/jovyan/shared

  spark-worker:
    image: bitnami/spark:3.5.0
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:8341
      - SPARK_WORKER_WEBUI_PORT=8342
    depends_on:
      - spark-master
    ports:
      - "8342:8342"
    volumes:
      - shared-workspace:/home/jovyan/shared

  jupyter:
    image: jupyter/pyspark-notebook:spark-3.5.0
    container_name: jupyter
    environment:
      - SPARK_MASTER=spark://spark-master:8341
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_DRIVER_OPTIONS="-Dspark.ui.port=4040"
    ports:
      - "8343:8888"
      - "4040:4040"
    volumes:
      - ../../projects:/home/jovyan/work
      - shared-workspace:/home/jovyan/shared
    depends_on:
      - spark-master
      - spark-worker
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''

volumes:
  shared-workspace:
  spark-events: